### PR TITLE
Handle errors properly

### LINKED ISSUE #36: Catch `NoSuchAlgorithmException` properly

### PR DESCRIPTION
**Pull request by ioannanedelcu**
Fixes #36

### CODE REVIEW

**Review by nd0761 — APPROVED** [review]

File: src/main/java/com/google/sps/servlets/ProfileImage.java [hunk 1]
```diff
@@ -52,8 +54,10 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
       InputStream fileInputStream = filePart.getInputStream();
 
       UserImage.uploadObject("theglobetrotter-step-2020", fileName, fileInputStream);
-    } catch (Exception e) {
-      // TODO(#14): Catch more specific exceptions.
+    } catch (EntityNotFoundException e) {
+      response.getWriter().println("<p>Error getting user from datastore!</p>");
```
Comment (conradgrobler) [inline src/main/java/com/google/sps/servlets/ProfileImage.java:58]: This will not be seen by the user if the redirect still happens further down in the code.

Also (probably for a different PR), the details of the exception should be logged somewhere (perhaps the cloud logging service) so that the people who operate the application can monitor whether it is healthy and working as expected.

**Review by conradgrobler — APPROVED** [review]

File: src/main/webapp/script.js [hunk 2]
```diff
@@ -20,28 +20,29 @@ function loadPage() {
...
+    const logButton = document.getElementById("log-button");
+    logButton.href = loginInfo.object.actionUrl;
+
+    // User is logged in.
+    if (loginInfo.object.loggedIn === true) {
+      document.getElementById("profile").style.visibility = "visible";
+      logButton.innerText = "LOGOUT";
+      document.getElementById("route-content").style.visibility = "visible";
+      // User is not logged in.
+    } else {
```
Comment (ipetr0v) [inline src/main/webapp/script.js:37]: I think it's better to put comments like this:
```

if (loginInfo.object.loggedIn === true) {
  // User is logged in.
  ...
} else {
  // User is not logged in.
  ...
```

**Review by ipetr0v — APPROVED** [review]

File: src/main/webapp/script.js (hunk 2 above)
Comment (ioannanedelcu) [reply src/main/webapp/script.js:37]: Done

File: src/main/java/com/google/sps/servlets/ProfileImage.java (hunk 1 above)
Comment (ioannanedelcu) [reply src/main/java/com/google/sps/servlets/ProfileImage.java:59]: Added TODO for that
